### ISSUE TITLE
rustup fails if sudo is not available

### ISSUE THREAD

**Issue by pwaller** [rust-lang-deprecated/rustup.sh#19]
I'm running in a minimal docker container, as root.

Rustup fails with `sudo: command not found`, even though I'm root and sudo is not necessary.

**Comment by genodeftest** [comment]
I think running as root should imply `--disable-sudo`. Running into the same issue.

**Comment by vi** [comment]
Also when failing, it does not save data (as in `--save`), so further re-run with `--disable-sudo` re-downloads.

**Comment by pwaller** [comment]
I did manage to install rust most recently when I tried so I must not have hit this problem. It's possible I installed via a binary image though.

I'm not interested in following this issue up, so I'm closing it. Please open a new issue if you want to keep tracking this.
