### ISSUE TITLE
"Empty installer version" error on Mint

### ISSUE THREAD

**Issue by edunham** [rust-lang-deprecated/rustup.sh#21]
Original issue was filed at https://github.com/rust-lang/rust/issues/24546 but it should probably be tracked here.

**Comment by strangeglyph** [comment]
I haven't been using Mint in a while, but I fired up my old VM and tried it again. Between back then and now, the issue seems to have been resolved. It works just fine now.

**Comment by steveklabnik** [comment]
Closing then, thanks for the follow-up @Boreeas
