### ISSUE TITLE
rustup failing on travis

### ISSUE THREAD

**Issue by mdinger** [rust-lang-deprecated/rustup.sh#3]
Rust-by-example is failing on travis at rustup. I've tried to figure out the issue [here](https://travis-ci.org/mdinger/rust-by-example) but haven't had any success. I'm not sure what the problem is. [This](https://travis-ci.org/mdinger/rust-by-example/builds/58365826#L87) was the original error.

---

[EDIT] The important part from the console

``` cmd
 $ curl -L https://static.rust-lang.org/rustup.sh | sudo sh -s -- --channel=nightly
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37166  100 37166    0     0  79838      0 --:--:-- --:--:-- --:--:--  107k
rustup: gpg available. signatures will be verified
rustup: downloading manifest for 'nightly'
gpg: WARNING: unsafe ownership on configuration file `/home/travis/.gnupg/gpg.conf'
rustup: downloading toolchain for 'nightly'
######################################################################## 100.0%
gpg: WARNING: unsafe ownership on configuration file `/home/travis/.gnupg/gpg.conf'
gpg: WARNING: unsafe ownership on configuration file `/home/travis/.gnupg/gpg.conf'
gpg: Signature made Mon 13 Apr 2015 10:27:08 AM UTC using RSA key ID 7B3B09DC
gpg: Good signature from "Rust Language (Tag and Release Signing Key) <rust-key@rust-lang.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 108F 6620 5EAE B0AA A8DD  5E1C 85AB 96E6 FA1B E5FE
     Subkey fingerprint: C134 66B7 E169 A085 1886  3216 5CB4 A934 7B3B 09DC
rustup: extracting installer
rustup: installing toolchain for 'nightly'
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'cargo'
install: installing component 'rust-docs'
    Rust is ready to roll.
0.01s
$ rustc --version
rustc: error while loading shared libraries: librustc_driver-4e7c5e5c.so: cannot open shared object file: No such file or directory
The command "rustc --version" exited with 127.
```

**Comment by brson** [comment]
Is this a new regression? I can't imagine offhand what change would have caused this.

Perhaps this particular type of Linux image doesn't have `/usr/local/lib` in `/etc/ld.so.conf`, so the dynamic linker isn't finding the install media? If that's the case then installing with either `--prefix=/usr` or setting `LD_LIBRARY_PATH=/usr/local/lib` would fix it.

**Comment by mdinger** [comment]
Pretty recent. [Here](https://travis-ci.org/rust-lang/rust-by-example/builds/57851837) is where I see it first (13 hours ago). The time of breakage is kinda hard to determine because travis was failing for a few days before that merged. Should be within a week though.

I'll try the fix and report back.

**Comment by mdinger** [comment]
That [fixed](https://travis-ci.org/mdinger/rust-by-example/builds/58376675) it. Is it fixable on your end or do there just need to be occasional instructions for this?

**Comment by brson** [comment]
@mdinger The underlying regression here should by fixed now by https://github.com/rust-lang/rustup/commit/fa82250ed51a65e24bf983d6b71e4b166a39e075
