### ISSUE TITLE
Script exits unsuccessfully although it ran successfully

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang-deprecated/rustup.sh#45]
Our build is broken since earlier today because the rust-up installer exits with a faulty status code despite all going fine. You can find the logs here: https://travis-ci.org/ligthyear/clippy-service/builds/114785173#L141

The last build that ran the script successful was 23h ago, before the big merge of #33, so the bug was presumably introduced in that change. We did not do any changes to the code in that time frame.

I am not at all familiar with the code base but a quick look lets me suspect that [not returning anything from `install_toolchain_from_dist`](https://github.com/rust-lang/rustup/blob/b788023812cb13b32a10e26042d2dd4973c5ca89/rustup.sh#L616-L769) and then [checking that  return value for `!= 0`](https://github.com/rust-lang/rustup/blob/b788023812cb13b32a10e26042d2dd4973c5ca89/rustup.sh#L496-L498) might be at fault here – but I am not a Bash expert.

**Comment by Ogeon** [comment]
I'm having the same problem when testing Rustful, but only with nightly. Stable and beta installs successfully.

**Comment by gnunicorn** [comment]
We are also running nightly.

**Comment by brson** [comment]
This should be fixed but will still take a few minutes to deploy.

**Comment by Ogeon** [comment]
Yep, I installs correctly now. Thank you!

**Comment by gnunicorn** [comment]
thanks @brson , I can confirm it works fine now: https://travis-ci.org/ligthyear/clippy-service/builds/115003443 !
