### ISSUE TITLE
Publish the signing key on keybase.io

### ISSUE THREAD

**Issue by lilyball** [rust-lang-deprecated/rustup.sh#5]
It would be great if the signing key were published on [keybase.io](https://keybase.io) (under the name "rustlang"). That way people like me who aren't particularly comfortable with GPG can use the Keybase process to determine whether the key should be trusted.

**Comment by cgaebel** [comment]
I have invites to contribute if needed.

**Comment by lilyball** [comment]
Oh, good point. So do I.

**Comment by edunham** [comment]
https://keybase.io/rust publishes the current Official Rust GPG Key, which is the one that appears in rustup.sh.
