### ISSUE TITLE
Non-interactive install

### ISSUE THREAD

**Issue by alexbowers** [rust-lang-deprecated/rustup.sh#83]
I am trying to provision a Vagrant machine, but have ran into problems with the provision of Rustup, partially caused (I think), because it isn't non-interactive.

I have tried `curl ... | sh -- -y`, however that doesn't work either. What would be preferable would be a generated script that assumes non-interactive.

For example `rustup-noninter.sh`.

**Comment by hlzhang** [comment]
try ```curl https://sh.rustup.rs -sSf | sh -s -- -y```
